<a href="https://colab.research.google.com/github/hashmiabrar1/Deep-Learning-Hands-on/blob/main/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

1.6.0+cu101


In [ ]:
#Tensors are multidimensional array. Same like numpy array
t_array=torch.Tensor([[1,2],[4,5]])
t_array

tensor([[1., 2.],
        [4., 5.]])

In [ ]:
tensor_uninitialized=torch.Tensor(3,3)
tensor_uninitialized
torch.numel(tensor_uninitialized)

9

In [ ]:
#Tensor with uninitialized random values of a specific data type.
tensor_int=torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0, -1,  0],
        [ 0,  1,  0],
        [ 0,  2,  0],
        [-2,  0,  0],
        [ 0,  0,  0]], dtype=torch.int32)

In [ ]:
#Initialize with ones or zeroes
tensor_ones=torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Get square matrix
tensor_sq=torch.eye(3)
tensor_sq

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#To fill all records with a particular value
tensor_new=torch.rand(3,3)
tensor_new.fill_(4)
tensor_new

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [ ]:
#To types of adding to the tensor. Below way of adding doesn't change the existing tensor. This is out of place addition
tensor_new.add(3)

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [ ]:
tensor_new

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [ ]:
#This is in place addition and it changes the value of the tensor.
tensor_new.add_(3)
tensor_new

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [ ]:
#Numpy operations
import numpy as np
np_array=np.array([1,2,3])
np_array

array([1, 2, 3])

In [ ]:
#Creating tensor from above np array
tensor=torch.from_numpy(np_array)
tensor

tensor([1, 2, 3])

In [ ]:
#Creating numpy array from tensor
np_array2=tensor.numpy()
np_array2

array([1, 2, 3])

In [ ]:
#Both numpy and tensor share the same memory.
np_array2[1]=9
tensor

tensor([1, 9, 3])

In [ ]:
#Splicing
tensor=torch.rand(3,4)
print(tensor)
print(tensor[:,1:])

tensor([[0.1706, 0.3983, 0.8053, 0.4549],
        [0.2672, 0.5414, 0.4370, 0.5227],
        [0.3114, 0.4947, 0.0767, 0.9618]])
tensor([[0.3983, 0.8053, 0.4549],
        [0.5414, 0.4370, 0.5227],
        [0.4947, 0.0767, 0.9618]])


In [ ]:
#Size
tensor.size()

torch.Size([3, 4])

In [ ]:
#Resize tensor
new_tensor=tensor.view(12)
new_tensor

tensor([0.1706, 0.3983, 0.8053, 0.4549, 0.2672, 0.5414, 0.4370, 0.5227, 0.3114,
        0.4947, 0.0767, 0.9618])

In [ ]:
#If data is changed in original tensor, data in view also changes
new_tensor2=tensor.view(4,3)
new_tensor2

tensor([[0.1706, 0.3983, 0.8053],
        [0.4549, 0.2672, 0.5414],
        [0.4370, 0.5227, 0.3114],
        [0.4947, 0.0767, 0.9618]])

In [ ]:
new_tensor3=tensor.view(-1,4)
new_tensor3

tensor([[0.1706, 0.3983, 0.8053, 0.4549],
        [0.2672, 0.5414, 0.4370, 0.5227],
        [0.3114, 0.4947, 0.0767, 0.9618]])

In [ ]:
tensor_sort, indices=torch.sort(new_tensor2)
tensor_sort

tensor([[0.1706, 0.3983, 0.8053],
        [0.2672, 0.4549, 0.5414],
        [0.3114, 0.4370, 0.5227],
        [0.0767, 0.4947, 0.9618]])

# **Computation Graph in PyTorch**

In [ ]:
#In tensorflow, it is define and run while in Torch, it allows to define. build and run at the same time i.e dynamically